"""add_ref_kato

Revision ID: 008ba9a56474
Revises: cf81686f6bc5
Create Date: 2026-02-27 17:32:51.536210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '008ba9a56474'
down_revision: Union[str, Sequence[str], None] = 'cf81686f6bc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_kato',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('full_name_ru', sa.String(), nullable=True),
    sa.Column('full_name_kz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref_kato')
    # ### end Alembic commands ###
