"""add_full_procurement_lifecycle

Revision ID: 45e7f937cd7c
Revises: d4f3d33d17b9
Create Date: 2026-02-26 14:00:02.794859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45e7f937cd7c'
down_revision: Union[str, Sequence[str], None] = 'd4f3d33d17b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_units',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('name_kz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('subjects',
    sa.Column('pid', sa.BigInteger(), nullable=False),
    sa.Column('bin', sa.String(), nullable=True),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('name_kz', sa.String(), nullable=True),
    sa.Column('is_customer', sa.Boolean(), nullable=True),
    sa.Column('is_supplier', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('pid')
    )
    op.create_index(op.f('ix_subjects_bin'), 'subjects', ['bin'], unique=True)
    op.create_table('announcements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('number_anno', sa.String(), nullable=True),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('org_bin', sa.String(), nullable=True),
    sa.Column('total_sum', sa.Numeric(), nullable=True),
    sa.Column('publish_date', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('ref_buy_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_bin'], ['subjects.bin'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_number_anno'), 'announcements', ['number_anno'], unique=False)
    op.create_table('lots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('trd_buy_id', sa.BigInteger(), nullable=True),
    sa.Column('lot_number', sa.String(), nullable=True),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('description_ru', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('count', sa.Numeric(), nullable=True),
    sa.Column('customer_bin', sa.String(), nullable=True),
    sa.Column('ref_lot_status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_bin'], ['subjects.bin'], ),
    sa.ForeignKeyConstraint(['trd_buy_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('contracts', sa.Column('trd_buy_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'subjects', ['customer_bin'], ['bin'])
    op.create_foreign_key(None, 'contracts', 'subjects', ['supplier_biin'], ['bin'])
    op.create_foreign_key(None, 'contracts', 'announcements', ['trd_buy_id'], ['id'])
    op.add_column('plans', sa.Column('ref_units_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_plans_ref_enstru_code'), 'plans', ['ref_enstru_code'], unique=False)
    op.create_foreign_key(None, 'plans', 'ref_units', ['ref_units_code'], ['code'])
    op.create_foreign_key(None, 'plans', 'subjects', ['subject_biin'], ['bin'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_constraint(None, 'plans', type_='foreignkey')
    op.drop_index(op.f('ix_plans_ref_enstru_code'), table_name='plans')
    op.drop_column('plans', 'ref_units_code')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'trd_buy_id')
    op.drop_table('lots')
    op.drop_index(op.f('ix_announcements_number_anno'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_subjects_bin'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_table('ref_units')
    # ### end Alembic commands ###
