"""add_ref_enstru_table

Revision ID: cf81686f6bc5
Revises: 45e7f937cd7c
Create Date: 2026-02-27 15:54:47.550368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf81686f6bc5'
down_revision: Union[str, Sequence[str], None] = '45e7f937cd7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ref_enstru',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('name_kz', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ref_enstru')
    # ### end Alembic commands ###
