"""initial_schema

Revision ID: d4f3d33d17b9
Revises: 
Create Date: 2026-02-24 18:35:28.765523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4f3d33d17b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('crdate', sa.DateTime(), nullable=True),
    sa.Column('contract_sum', sa.Numeric(), nullable=True),
    sa.Column('supplier_biin', sa.String(), nullable=True),
    sa.Column('customer_bin', sa.String(), nullable=True),
    sa.Column('ref_contract_status_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subject_biin', sa.String(), nullable=True),
    sa.Column('ref_enstru_code', sa.String(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('count', sa.Numeric(), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=True),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.Column('kato_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_units',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('pln_point_id', sa.BigInteger(), nullable=True),
    sa.Column('item_price', sa.Numeric(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('total_sum', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['pln_point_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_units')
    op.drop_table('plans')
    op.drop_table('contracts')
    # ### end Alembic commands ###
